adminUser:
  password: vault:frightgold/adminUser:password
  username: admin
dashboardAuthID: vault:frightgold:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:frightgold:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:frightgold/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:frightgold/prow:hmacToken
